# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1114, 844)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(-5, 1, 661, 861))
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(Dialog)
        self.listWidget_2.setGeometry(QtCore.QRect(710, 50, 371, 231))
        self.listWidget_2.setObjectName("listWidget_2")
        self.listWidget_3 = QtWidgets.QListWidget(Dialog)
        self.listWidget_3.setGeometry(QtCore.QRect(710, 420, 371, 201))
        self.listWidget_3.setObjectName("listWidget_3")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(710, 630, 371, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label_spisok_zamitok = QtWidgets.QLabel(Dialog)
        self.label_spisok_zamitok.setGeometry(QtCore.QRect(720, 20, 111, 16))
        self.label_spisok_zamitok.setObjectName("label_spisok_zamitok")
        self.label_spisok_tegiv = QtWidgets.QLabel(Dialog)
        self.label_spisok_tegiv.setGeometry(QtCore.QRect(710, 400, 91, 16))
        self.label_spisok_tegiv.setObjectName("label_spisok_tegiv")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(740, 290, 301, 91))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_stvoritu = QtWidgets.QPushButton(self.widget)
        self.pushButton_stvoritu.setObjectName("pushButton_stvoritu")
        self.horizontalLayout_2.addWidget(self.pushButton_stvoritu)
        self.pushButton_vidalitul = QtWidgets.QPushButton(self.widget)
        self.pushButton_vidalitul.setObjectName("pushButton_vidalitul")
        self.horizontalLayout_2.addWidget(self.pushButton_vidalitul)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.pushButton_zberegty = QtWidgets.QPushButton(self.widget)
        self.pushButton_zberegty.setObjectName("pushButton_zberegty")
        self.verticalLayout_3.addWidget(self.pushButton_zberegty)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(740, 680, 341, 101))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_dodatu = QtWidgets.QPushButton(self.widget1)
        self.pushButton_dodatu.setObjectName("pushButton_dodatu")
        self.horizontalLayout_3.addWidget(self.pushButton_dodatu)
        self.pushButton_shykatu = QtWidgets.QPushButton(self.widget1)
        self.pushButton_shykatu.setObjectName("pushButton_shykatu")
        self.horizontalLayout_3.addWidget(self.pushButton_shykatu)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_spisok_zamitok.setText(_translate("Dialog", "Список заміток:"))
        self.label_spisok_tegiv.setText(_translate("Dialog", "Список тегів:"))
        self.pushButton_stvoritu.setText(_translate("Dialog", "створити замітку"))
        self.pushButton_vidalitul.setText(_translate("Dialog", "видалити замітку"))
        self.pushButton_zberegty.setText(_translate("Dialog", "Зберегти замітку"))
        self.pushButton_dodatu.setText(_translate("Dialog", "додати до замітки"))
        self.pushButton_shykatu.setText(_translate("Dialog", "шукати замітки по тегу"))
        self.pushButton_5.setText(_translate("Dialog", "відкріпити від замітки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
